### PR TITLE
:sparkles: Major update for version 2.0.0

### LINKED ISSUE #7: Support for multiply controllers
Users of TECH Controllers can own multiply controllers within one household, ex. one L-7 to control their floor heating system and other, ex. WiFi 8S to control their heaters on second floor. Currently this integration is able to handle one controller which is first returned by TECH API. 

The aim of this enhancement is to provide support for multiply controllers within one household.

### PR DESCRIPTION
**Pull request by anarion80**
# Hello!

@mariusz-ostoja-swierczynski has been kind enough to add me as collaborator to this repo and I would like to take the opportunity to bring the integration to next version.

I was working on the side (see [here](https://github.com/anarion80/tech) for detailed list of development progress) to modernize the integration, add features from dev branch, other forks, keep it up to date with Home Assistant development.

## What is changed?

- Multi-controller support, each controller can be selected individually during config flow
- Tiles support for all that is visible in emodul demo (username: `test`, password: `test`)
- Zones as devices with temperature, battery, humidity sensors linked to them
- Tile translation directly from emodul API
- `DataUpdateCoordinator` for all entities
- Config flow abort for existing controller
- Migration from v1
- Updated development environment with .devcontainer
- Linters for python, yaml, markdown
- Automated release notes and releasing via workflow actions
- HACS readiness
- Good practices from Home Assistant

I have been using it with my M-9r and it works fine, so I'm fairly confident this PR is ok to merge, and I will merge it some time soon, but it would be great if the community can just take it and test it. Especially the authors mentioned in the README whom I will try to engage.

## Fixes

Fixes #7 #15 #31 #37 #48 #49 #52

### CODE REVIEW

**Comment by czystyl** [comment]
Great work @anarion80! I've tested it with my Tech Controller, and this version is working better than the main version. 👏

**Comment by jontofront** [comment]
@anarion80  which version we can use  v2 branch or wait for the merge?
If need some test manual new beta version or changes I can do it :)

**Comment by anarion80** [comment]
> @anarion80 which version we can use v2 branch or wait for the merge? If need some test manual new beta version or changes I can do it :)

take v2 if you are impatient or want to test 😄, otherwise wait for the merge. I think I'll merge next week.

**Comment by MichalKrasowski** [comment]
Tested locally on my HA, looks good for wifi-ot and L8

**Pull request merged**
