### PR TITLE
Tiles  -Support for OPOP: ST-581v9 Premium unit and maybe for other controllers which are using the same tiles

### PR DESCRIPTION
**Pull request by alevike**
Support for OPOP: ST-581v9 Premium unit

I have to mention that I'm not a developer. I'm sure that the code can be optimized... This variant is working fine for my controller from a couple of months.

It is not supporting any setting update or value change for tiles - it's more like for monitoring. 

image

image

### CODE REVIEW

**Comment by jaanek** [comment]
Curious why was it closed? Was it abandoned as not working?

**Comment by nepozs** [comment]
The whole project is abandoned, just try to find active fork.

**Comment by mariusz-ostoja-swierczynski** [comment]
Those features #7 and #15  are finally done in dev branch. @jaanek @nepozs @alevike  please test it out and report any issues. I will marge is to master hopefully soon.

Few words of explanations it took so long. During the development of this feature I was trying to get some simple support from Tech (answer on their APIs), but they didn't provide it although they promised it. After long time of reminding myself to them, winter was over and I lost both time and motivation. This winter I found out how many people were interested in this integration and even some people put effort for further development of this integration and so I regained bit of motivation. Anyway I don't have anything against forking this repo and moving forward if I lost it again :)

**Comment by jaanek** [comment]
I have a ST-581v9 Premium unit and it's working now. Thank you.
However I have a valve for which it does not show a temperature, only shows "openingPercentage". There is a tile named "Built-in valve" with the following content:
```
{
      "id": 1012,
      "parentId": 0,
      "type": 23,
      "menuId": 2229,
      "orderId": null,
      "visibility": true,
      "params": {
        "description": "Built-in valve",
        "workingStatus": true,
        "valveNumber": 1,
        "currentTemp": 325,
        "returnTemp": 68,
        "setTempCorrection": 0,
        "openingPercentage": 11,
        "valvePump": 1,
        "boilerProtection": 0,
        "returnProtection": 0,
        "setTemp": 34,
        "txtId": 992
      }
    },
```
There is a "currentTemp" and "setTemp". I am mostly interested in "currentTemp" to extract that into a temp entity. If you have a chance could you please give me some pointers in code where I could add code for that?
Also as a second question, I suppose you are already familiar with emodul api, do they have an api way to start, stop pid operation? The way you can do it via their UI interface app with "Firing up" and "Dumping" actions?

**Comment by jaanek** [comment]
@mariusz-ostoja-swierczynski To add to my last message ... or whether you might to know also if their api supports changing "Operation modes" also? as it's possible via their app UI.

**Pull request closed without merging**
